const NAMESPACE = 'LIBRARIES_ACTION';

const GET_LIBRARIES = `${NAMESPACE}/GET_LIBRARIES`;
const GET_LIBRARIES_SUCCESS = `${NAMESPACE}/GET_LIBRARIES_SUCCESS`;
const GET_LIBRARIES_ERROR = `${NAMESPACE}/GET_LIBRARIES_ERROR`;
const DELETE_LIBRARY = `${NAMESPACE}/DELETE_LIBRARY`;
const DELETE_LIBRARY_SUCCESS = `${NAMESPACE}/DELETE_LIBRARY_SUCCESS`;
const DELETE_LIBRARY_ERROR = `${NAMESPACE}/DELETE_LIBRARY_ERROR`;
const CREATE_LIBRARY = `${NAMESPACE}/CREATE_LIBRARY`;
const CREATE_LIBRARY_SUCCESS = `${NAMESPACE}/CREATE_LIBRARY_SUCCESS`;
const CREATE_LIBRARY_ERROR = `${NAMESPACE}/CREATE_LIBRARY_ERROR`;
const UPDATE_LIBRARY = `${NAMESPACE}/UPDATE_LIBRARY`;
const UPDATE_LIBRARY_SUCCESS = `${NAMESPACE}/UPDATE_LIBRARY_SUCCESS`;
const UPDATE_LIBRARY_ERROR = `${NAMESPACE}/UPDATE_LIBRARY_ERROR`;

export default {
  GET_LIBRARIES,
  GET_LIBRARIES_SUCCESS,
  GET_LIBRARIES_ERROR,
  DELETE_LIBRARY,
  DELETE_LIBRARY_SUCCESS,
  DELETE_LIBRARY_ERROR,
  CREATE_LIBRARY,
  CREATE_LIBRARY_SUCCESS,
  CREATE_LIBRARY_ERROR,
  UPDATE_LIBRARY,
  UPDATE_LIBRARY_SUCCESS,
  UPDATE_LIBRARY_ERROR,
};
