version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build & Test
          command: yarn build:ci
