const NAMESPACE = 'AUTHN';
const SIGN_IN = `${NAMESPACE}/SIGN_IN`;
const SIGN_IN_SUCCESS = `${NAMESPACE}/SIGN_IN_SUCCESS`;
const SIGN_IN_ERROR = `${NAMESPACE}/SIGN_IN_ERROR`;

const SIGN_OUT = `${NAMESPACE}/SIGN_OUT`;
const SIGN_OUT_SUCCESS = `${NAMESPACE}/SIGN_OUT_SUCCESS`;
const SIGN_OUT_ERROR = `${NAMESPACE}/SIGN_OUT_ERROR`;

export default {
  SIGN_IN,
  SIGN_IN_SUCCESS,
  SIGN_IN_ERROR,
  SIGN_OUT,
  SIGN_OUT_SUCCESS,
  SIGN_OUT_ERROR,
};
