const NAMESPACE = 'NOTIFICATIONS';
const PUSH_NOTIFICATION = `${NAMESPACE}/PUSH_NOTIFICATION`;
const DISMISS_NOTIFICATION = `${NAMESPACE}/DISMISS_NOTIFICATION`;

export default {
  PUSH_NOTIFICATION,
  DISMISS_NOTIFICATION,
};
